In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import math

In [3]:
fbs_defense = pd.read_csv('/home/blair/cognixia_workspace/CFB_Statistics/CFB_Stats/All FBS Teams (Defense).csv')
fbs_defense

,Player,Team,Int,Yds,Avg,Lg,TD,Solo,Ast,Tot,Sack,YdsL,Stat Type
0,Andre Cisco,SYR,7,47,6.71,39,0,46,14,60,0.0,0.0,Defense
1,Hamp Cheevers,BC,7,135,19.29,81t,1,27,12,39,0.0,0.0,Defense
2,Nate Brooks,UNT,6,15,2.50,13,0,48,19,67,0.0,0.0,Defense
3,Jaylinn Hawkins,CAL,6,39,6.50,29,0,25,8,33,0.0,0.0,Defense
4,Richie Grant,UCF,6,40,6.67,25,0,68,40,108,0.0,0.0,Defense
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Cameron Lewis,BUFF,3,37,12.33,37,0,23,9,32,0.0,0.0,Defense
96,Michael Ojemudia,IOWA,3,38,12.67,29,0,23,16,39,0.0,0.0,Defense
97,L'Jarius Sneed,LT,3,43,14.33,19,1,44,15,59,1.5,6.0,Defense
98,Bryce Thompson,TENN,3,45,15.00,21,0,24,10,34,1.0,6.0,Defense
99,Jhavonte Dean,MIA,3,46,15.33,25,0,5,12,17,0.0,0.0,Defense

In [9]:
leading_tacklers = fbs_defense.sort_values(['Tot'], ascending=False).apply(lambda tackles:tackles)
leading_tacklers

,Player,Team,Int,Yds,Avg,Lg,TD,Solo,Ast,Tot,Sack,YdsL,Stat Type
10,Tre Watson,MD,5,51,10.20,36t,1,70,44,114,1.0,7.0,Defense
27,Cooper Edmiston,TULS,4,34,8.50,26,0,47,66,113,0.5,1.0,Defense
90,T.J. Edwards,WISC,3,31,10.33,28,0,73,39,112,3.0,19.0,Defense
4,Richie Grant,UCF,6,40,6.67,25,0,68,40,108,0.0,0.0,Defense
48,Reed Blankenship,MTSU,4,122,30.50,100t,1,71,36,107,1.0,3.0,Defense
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,V.J. Banks,CSU,3,0,0.00,0,0,18,9,27,0.0,0.0,Defense
11,Adrian Frye,TTU,5,55,11.00,48t,1,17,4,21,0.0,0.0,Defense
99,Jhavonte Dean,MIA,3,46,15.33,25,0,5,12,17,0.0,0.0,Defense
61,Mike Reynolds,ARMY,3,0,0.00,0,0,10,4,14,0.0,0.0,Defense
55,Linwood Crump,TEM,3,0,0.00,0,0,12,1,13,0.0,0.0,Defense